 var name1 = "sweety";
 var name2 = "cutie";
 console.log('Before Swap:' , 'name1==>' , name1 , 'name2==>' , name2);
console.log('After Swap:' , 'name1==>' , name2 , 'name2==>' , name1);
console.log('---------------------*****-----------------------');
var num1 = 100; 
var num2 = 200;
var num3 = 300;
console.log( 'Before Swap :' ,'num1=>', num1, ' num2=> ', num2,'num3=> ', num3);
console.log('After Swap :' ,'num1=> ', num3, ' num2=> ', num2, 'num3=>', num1);
